### ISSUE TITLE
Feature request: Add option to append to current form field value

### ISSUE THREAD

**Issue by marcelimati** [hackingharold/ngx-dropzone#52]
I suggest making a parameter in input field or something that will change current behaviour of inserting files. At this moment each time you drag/select files, it creates array of files from 0. Would be nice to have option for appending to array instead of re-assigning array of files.

**Comment by hackingharold** [comment]
Hi @marcelimati,

thanks for your feature request. The current behavior is actually intended because the form/input state management should be handled by the library consumer. From the library perspective, I don't know how you store the selected files.

What exactly would be your use case for this?

**Comment by marcelimati** [comment]
Actually nevermind, because I could just add to array file elements whenever input changes, for example I would add 2 files, two times. Then I would have total 4 files in my array, even though in this library array there are only 2. Then if I want to remove some files i would just splice my array, so don't need to make that change in the library.

Cheers.

**Comment by hackingharold** [comment]
Yeah, that's exactly what I thought you would do. 👍🏼

**Comment by mpflanzer** [comment]
I have the same use case that I would like the behavior to be to add files instead of overwriting the previous ones. In my case the dropzone is part of a bigger form-group that is eventually going to be submitted.

The solution above works but it means I need to create an extra form control for the dropzone and copy file entries to the form control of the form group. More convenient would be to just use the form control that is already in the group and have an option to tell the dropzone to append to the form control it's using instead of just setting the value.

**Comment by hackingharold** [comment]
Hi @mpflanzer,

I understand this use case and will think about a possible solution. 👍🏼

**Comment by hackingharold** [comment]
Hi @mpflanzer 

I added a new `mode` property and released it with v17.1.0. Please test it out and see if this works for you.

**Comment by mpflanzer** [comment]
Took me a bit longer, but it's working as expected for me. Thanks!

**Comment by hackingharold** [comment]
You would have to implement that on your own. I recommend to use a `Set` to avoid duplicate file names.

**Comment by leonp5** [comment]
Thank you for your answer :slightly_smiling_face:
