### ISSUE TITLE
Any way to make its markup work on Angular 15?

### ISSUE THREAD

**Issue by alexandis** [hackingharold/ngx-dropzone#73]
Hi.

Was looking for _Drop Zone_ component for Angular **15** we use...
The old version (predecessor) is created for up to Angular **13** (and we would not like to use an outdated version of _Drop Zone_).
Your version supports Angular **16+**. Why there's a gap and no support for Angular **14-15**? :)
Anyway, I've installed your version using `--legacy-peer-deps` key. And as I can see from the debug, the dropped folder files are added to the _form_. But there's nothing in the markup and I can't see the way to fix it (the zone below actually does have files added):
![image](https://github.com/hackingharold/ngx-dropzone/assets/6149843/bd372a75-6958-4ab7-8643-5437990bcb5d)

Could you please suggest the way I can fix the markup somehow?

**Comment by hackingharold** [comment]
Hi there, thanks for using the dropzone. 
Could you please provide a code snippet of your form field and the Angular and ngx-dropzone versions used?

**Comment by hackingharold** [comment]
Indeed, the dropzone component itself does not include any markup for file previews because people are very opinionated about them depending on the use case. So I did not want to enforce any styling or pattern.

Your workaround is actually the desired usage, you display the files by looping over the `files` array.
More info [here](https://github.com/hackingharold/ngx-dropzone?tab=readme-ov-file#file-previews).
